export default {
  products: [
    {
      _id: '1',
      name: 'Ditto Family',
      category: 'Toy',
      image: '/images/product-1.jpg',
      price: 88,
      brand: 'Meidamong Company',
      rating: 4.5,
      numReviews: 123,
      countInStock: 6,
      description: 'very cute and soft',
    },
    {
      _id: '2',
      name: 'Ditto Family2',
      category: 'Toy',
      image: '/images/product-1.jpg',
      price: 88,
      brand: 'Meidamong Company',
      rating: 3.5,
      numReviews: 1000,
      countInStock: 6,
      description: 'very cute and soft',
    },
    {
      _id: '3',
      name: 'Ditto Family3',
      category: 'Toy',
      image: '/images/product-1.jpg',
      price: 88,
      brand: 'Meidamong Company',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description: 'very cute and soft',
    },
    {
      _id: '4',
      name: 'Ditto Family4',
      category: 'Toy',
      image: '/images/product-1.jpg',
      price: 88,
      brand: 'Meidamong Company',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description: 'very cute and soft',
    },
    {
      _id: '5',
      name: 'Ditto Family5',
      category: 'Toy',
      image: '/images/product-1.jpg',
      price: 88,
      brand: 'Meidamong Company',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description: 'very cute and soft',
    },
    {
      _id: '6',
      name: 'Ditto Family6',
      category: 'Toy',
      image: '/images/product-1.jpg',
      price: 88,
      brand: 'Meidamong Company',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description: 'very cute and soft',
    },
  ],
};
